/*
 * DO NOT EDIT THIS FILE, your changes will be overwritten
 * This is an automatically generated file.
 * It was generated with uasm, the microassembler, on
 * Wed Nov 27 15:21:25 2019
 */

module MICROCODE_ROM_template();

/*
 * wires and registers for the design
 */

wire [44:0]  ROM_out;
reg  [10:0]  CAR;

MICROCODE_ROM MICROCODE_ROM1(
   .ADDR_in(CAR),
   .ROM_out(ROM_out));

wire [ 2:0]  ASEL;
wire [ 2:0]  BSEL;
wire [ 2:0]  DSEL;
wire [ 3:0]  FSEL;
wire [ 3:0]  UPDF;
wire         MUX1;
wire [ 3:0]  MUX2;
wire [15:0]  DATA;
wire [ 6:0]  MISC;

assign                 ASEL = ROM_out[44:42];    // bit size:3
assign                 BSEL = ROM_out[41:39];    // bit size:3
assign                 DSEL = ROM_out[38:36];    // bit size:3
assign                 FSEL = ROM_out[35:32];    // bit size:4
assign                 UPDF = ROM_out[31:28];    // bit size:4
assign                 MUX1 = ROM_out[27];       // bit size:1
assign                 MUX2 = ROM_out[26:23];    // bit size:4
assign                 DATA = ROM_out[22: 7];    // bit size:16
assign                 MISC = ROM_out[ 6: 0];    // bit size:7
endmodule
